# Generated by Django 5.0.6 on 2026-05-31 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('SERVER', 'Enterprise Server'), ('WORKSTATION', 'Employee Workstation'), ('NETWORK', 'Network Router/Switch'), ('CLOUD', 'Cloud Repository')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='IncidentTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('nist_stage', models.CharField(choices=[('PREPARATION', '1. Preparation'), ('DETECTION_ANALYSIS', '2. Detection & Analysis'), ('CONTAINMENT_ERADICATION', '3. Containment, Eradication & Recovery'), ('POST_INCIDENT', '4. Post-Incident Activity'), ('CLOSED', '5. Resolved / Closed')], default='PREPARATION', max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='incident_core.asset')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
