# Generated by Django 6.0.5 on 2026-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentticket',
            name='category',
            field=models.CharField(choices=[('IT_SUPPORT', 'IT Support'), ('SECURITY_BREACH', 'Security Breach')], default='IT_SUPPORT', max_length=20),
        ),
    ]
